#!/bin/bash

##
directory=$(zenity --file-selection --directory)
source "/home/$USER/anaconda3/etc/profile.d/conda.sh"

##
arr=()
IFS=$'\n' read -r -d '' -a arr < <(conda env list | awk 'NR>=3' | awk '{print $1}' && printf '\0')
ename=$(zenity --entry --title "Choose environment" --text "Environment name" "${arr[@]}")

##
nautilus "$directory" &
conda activate "$ename"
jupyter notebook --notebook-dir "$directory"
